const db = require('./db/oracleConnection');

async function createListingsTable() {
  console.log('Creating LISTINGS table for house rental application...');
  
  try {
    // Check if LISTINGS table already exists
    const tableExists = await db.execute(`
      SELECT table_name FROM user_tables WHERE table_name = 'LISTINGS'
    `);
    
    if (tableExists.rows.length > 0) {
      console.log('✅ LISTINGS table already exists');
      return;
    }
    
    // Create LISTINGS table with simpler syntax
    console.log('Creating LISTINGS table...');
    await db.execute(`
      CREATE TABLE listings (
        listing_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id NUMBER NOT NULL,
        title VARCHAR2(200) NOT NULL,
        description VARCHAR2(4000),
        image_url VARCHAR2(4000),
        address VARCHAR2(300),
        latitude NUMBER,
        longitude NUMBER,
        owner_phone VARCHAR2(40),
        bedrooms NUMBER,
        bathrooms NUMBER,
        area_sqft NUMBER,
        furnished VARCHAR2(30),
        verified NUMBER(1) DEFAULT 0,
        deposit NUMBER,
        available_from DATE,
        contact_start VARCHAR2(10),
        contact_end VARCHAR2(10),
        price NUMBER NOT NULL,
        total_units NUMBER DEFAULT 1,
        available_units NUMBER DEFAULT 1,
        city VARCHAR2(120),
        category VARCHAR2(60),
        created_at DATE DEFAULT SYSDATE,
        updated_at DATE
      )
    `);
    
    console.log('✅ LISTINGS table created successfully');
    
    // Create indexes
    console.log('Creating indexes...');
    await db.execute('CREATE INDEX idx_listings_geo ON listings(latitude, longitude)');
    await db.execute('CREATE INDEX idx_listings_price ON listings(price)');
    await db.execute('CREATE INDEX idx_listings_city ON listings(city)');
    await db.execute('CREATE INDEX idx_listings_owner ON listings(owner_id)');
    
    console.log('✅ Indexes created successfully');
    
    // Create RATINGS table if it doesn't exist
    console.log('Creating RATINGS table...');
    const ratingsExists = await db.execute(`
      SELECT table_name FROM user_tables WHERE table_name = 'RATINGS'
    `);
    
    if (ratingsExists.rows.length === 0) {
      await db.execute(`
        CREATE TABLE ratings (
          rating_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          listing_id NUMBER NOT NULL,
          user_id NUMBER NOT NULL,
          score NUMBER CHECK (score BETWEEN 1 AND 5) NOT NULL,
          created_at DATE DEFAULT SYSDATE
        )
      `);
      console.log('✅ RATINGS table created successfully');
    } else {
      console.log('✅ RATINGS table already exists');
    }
    
    console.log('\n🎉 All tables created successfully!');
    console.log('The House Rental application database is now ready!');
    
  } catch (err) {
    console.error('❌ Error creating tables:', err.message);
    console.error('Error details:', err);
  }
}

createListingsTable();
